### ISSUE TITLE
Login - Error al cargar imagen 

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#66]
## Proceso

1. Entrar a la aplicación
2. Navegar al login

## Resultado esperado

Se espera que las imagenes, fuentes, estilos y/o videos carguen con normalidad

## Resultado actual

La imagen a la izquierda del login, no está cargando correctamente. Al ser un `div`, tampoco tiene un texto alternativo.

## Captura

<img width="1435" alt="Screenshot 2024-01-17 at 09 45 42" src="https://github.com/biandeb/final-project-group-1/assets/83432755/b8c86366-6755-4473-80fa-f9197136305f">

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/e265127b54844a64e0f91fe811296471bc22c07b . Adjunto commit se corrige el error de carga de imagen del login y se le agrega el alt en caso de no cargar la imagen
