### ISSUE TITLE
Redireccionamiento de netlify

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#67]
## Proceso

Ingrear a cualquier pagina de la web

## Resultado esperado

Se espera que al recargar la página, la misma refresque la información actual.

## Resultado actual

Actualmente se presenta un error de netlify

## Captura

https://github.com/biandeb/final-project-group-1/assets/83432755/0ad2abbe-6c2f-4ca1-b527-2c8d3c23f9c2

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/8fde16efec06652f2988699c5eb0f52f73c54b3c. Adjunto commit _redirects se utiliza para configurar redirecciones en un entorno de alojamiento estático y en este caso, la configuración específica redirige todas las solicitudes a la ruta raíz con un código de estado 200.
