### ISSUE TITLE
Admin - Editar productos

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#68]
## Proceso

1. Ir al logina
2. Ingresar como administrador
3. Editar los productos

## Resultado esperado

Se espera que al editar los productos, seleccionando un label de la opcion **Is available**, se deshabilite o habilite en su defecto al mismo que se está accionando.

Por ejemplo, si acciono el de **Strip roast**, solo este elemento se debería editar

## Resultado actual

Al hacer click en el label, siempre se esta accionando el primer elemento.

## Captura

https://github.com/biandeb/final-project-group-1/assets/83432755/4fec46d7-1c9b-4fec-af75-37f039c0eeca

## Notas

> Recuerden que en este caso, elementos labels deben tener asociado un solo input. 

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/7db66be4cd381be4927776457075fed7960ff911. Adjunto commit se soluciona el problema agregandole el index al id asi toma el index de cada producto agregado y nose altera con los demas
