### ISSUE TITLE
Checkout - Loop infinito

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#69]
## Proceso

1. Registrarse o iniciar con un usuario común
2. Cargar productos al carrito
3. Ir a checkout

## Resultado esperado

Se espera que al navegar al carrito, se pueda finalizar la compra

## Resultado actual

La pantalla de checkout quedá en un loop infinito

## Captura

<img width="1439" alt="image" src="https://github.com/biandeb/final-project-group-1/assets/83432755/8f898867-e26b-47d5-bac1-f4ee427e4ddc">

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/a1ea3eac29d4c4cb23fea488d426bec5ec1be0c9 .Adjunto commit se arregla el loop infinito quitanto el loeader de sweetalert2 y mejoramos el error usando alert de boostrap como ayuda visual para los usuarios.
