### ISSUE TITLE
Navegación en Mobile

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#70]
## Proceso

1. Entrar en modo Mobile
2. Iniciar sesión
3. Navegar en los distintos tabs

## Resultado esperado

Se espera que al tener una sesión iniciada, los tabs estén validados para no pedir nuevamente un login.

## Resultado actual

Al ir hacia home, presenta la pantalla de autenticación a un usuario que ya inició sesión

## Captura

https://github.com/biandeb/final-project-group-1/assets/83432755/44a5a2fd-10dc-4104-85a6-c4c4dcdc2225

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/8257305ed154de48ea95533bbd5d2f77835264ea . Adjunto commit se probo  varias veces el error pero no aparecio en ningun momento como en el ejemplo dado. Ante cualquier problema con la redireccion se agrego una validacion en el boton continue para verificar si esta logeado te envie a order y si no estas logeado te envia a logearte.
