### ISSUE TITLE
Eliminar console logs

### ISSUE THREAD

**Issue by castromaciel** [biandeb/final-project-group-1#71]
Para una estructura de proyecto mucho más limpia, se recomienda eliminar todos los console.logs que son para el desarrollador.

<img width="879" alt="image" src="https://github.com/biandeb/final-project-group-1/assets/83432755/67ea0cbb-7991-4951-9a81-8aa5f73f5e15">

**Comment by CardozoMartin** [comment]
https://github.com/biandeb/final-project-group-1/commit/e265127b54844a64e0f91fe811296471bc22c07b aqui adjunto el commit donde se realizaron la limpieza del codigo de todos los console.log del front
